#Create a deployment by using the mongo:3.6.6 image from Docker Hub
#Use mongodb as the deployment name
#While creating the mongodb deployment, apply the username and password defined in secret
#Use the names as follows `MONGO_INITDB_ROOT_USERNAME` - username, `MONGO_INITDB_ROOT_PASSWORD` - password
#Use containerPort 27017
apiVersion: apps/v1

---
#Create the service of type ClusterIP and use the above created deployment as selector
#Use port 27017
#Use mongodb as the service name
apiVersion: v1
