#Create a deployment by using the image pushed to Docker Hub
#Use containerPort 8081
#While creating the deployment, get the values from ConfigMap and secret and follow the below instructions
#Use the name as `GREETING` for the key which has to accessed from ConfigMap, which is used in the SpringBoot application
#Use the names as follows `MONGO_INITDB_ROOT_USERNAME` - username, `MONGO_INITDB_ROOT_PASSWORD` - password for the values access from secret
apiVersion: apps/v1

---

#Create the service of type NodePort and use the above created deployment as selector
#Use port 8081
apiVersion: v1
