#Sbservice should start at 8081
server:
   port: 8081

sb:
  k8:
    message : Hello!!!

spring:
   data:
     mongodb:
          host: mongodb
          port: 27017
          username:  #assign value to username defined in deployment with key MONGO_INITDB_ROOT_USERNAME
          password:  #assign value to password defined in deployment with key MONGO_INITDB_ROOT_PASSWORD
          database: admin
          ssl: true